matrix:
  include:
    - language: java
      install: true
      jdk:
        - openjdk11
      script:
        - cd java
        - ./gradlew test
    - language: kotlin
        install: true
        jdk:
          - openjdk11
        script:
          - cd kotlin
          - ./gradlew test
    - language: scala
      scala:
        - 2.12.8
      script:
        - cd scala
        - sbt test
    - language: python
      matrix:
        include:
          - python: 3.7
            dist: xenial
            sudo: true
      install:
        - pip install -r requirements.txt
      before_script:
        - flake8
      script:
        - cd python
        - pytest
