matrix:
  include:
    - language: java
      install: true
      jdk:
        - openjdk11
      script:
        - ./gradlew test
    - language: scala
      scala:
        - 2.12.8
      script:
        - sbt test
